 name: Build and Test
 on:
   push:
     branches:
       - '**'

 jobs:
   build-and-test-linux:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Install dependencies
         run: |
           sudo apt-get install xvfb

       - name: Start virtual framebuffer
         run: |
           export DISPLAY=:99
           Xvfb :99 -screen 0 1280x1024x24 &

       - name: Build
         run: |
           make run

       - name: Run client
         run: |
           cd build
           ./r-type_client 1

       - name: Run Server
         run: |
           cd build
           ./r-type_server 0

#   build-and-test-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#
#       - name: Install dependencies
#         shell: powershell
#         run: |
#           choco install -y vcbuildtools
#           choco install -y cmake
#
#       - name: Add MSBuild to PATH
#         shell: powershell
#         run: setx PATH "%PATH%;%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
#
#
#       - name: Build server
#         shell: powershell
#         run: |
#           cd Server\
#           cmake --build . --config Release
#
#       - name: Run server
#         shell: powershell
#         run: |
#           cd Server\x64\Release
#           r-type_server.exe
#
#       - name: Build client
#         shell: powershell
#         run: |
#           cd Client\
#           cmake .
#           msbuild.exe r-type_client.sln /p:Configuration=Release
#
#       - name: Run client
#         shell: powershell
#         run: |
#           cd Client\x64\Release
#           r-type_client